name: Quality Check
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repo
              uses: actions/checkout@v2

            - name: Set up node
              uses: actions/setup-node@v1
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Run linter
              run: npm run lint
